export const WORDLE_WORDS = [
    { word: "apple"},
    { word: "table", hint: "You put things on it" },
    { word: "cloud", hint: null },
    { word: "pencil", hint: null },
    { word: "ocean", hint: "A vast body of salt water" },
    { word: "guitar", hint: "A musical instrument with six strings" },
    { word: "mountain", hint: "A large landform that rises above the surrounding land" },
    { word: "window", hint: "A transparent opening in a wall" },
    { word: "bicycle"},
    { word: "sun", hint: "A star at the center of our solar system" },
    { word: "moon", hint: null },
    { word: "elephant", hint: "The largest land animal" },
    { word: "shadow", hint: "A dark area produced by blocking light" },
    { word: "bridge", hint: "A structure built to span a physical obstacle" },
    { word: "desert", hint: "A barren area of landscape with little precipitation" },
    { word: "clock", hint: "A device used to measure and indicate time" },
    { word: "whisper", hint: "To speak very softly" },
    { word: "candle", hint: "A wax block with a wick used for light" },
    { word: "island", hint: "A piece of land surrounded by water" },
    { word: "camera", hint: "A device used to take photographs" },
    { word: "dragon", hint: "A mythical creature that breathes fire" },
    { word: "forest", hint: "A large area covered with trees" },
    { word: "diamond", hint: "A precious stone known for its hardness" },
    { word: "volcano", hint: "A mountain that erupts with lava" },
    { word: "puzzle", hint: null },
    { word: "mirror", hint: "A surface that reflects an image" },
    { word: "ladder", hint: "A tool used to climb to higher places" },
    { word: "library", hint: "A place where books are kept" },
    { word: "rocket", hint: "A vehicle designed for space travel" },
    { word: "whistle", hint: "A high-pitched sound made by blowing air" },
    { word: "garden", hint: "An area for growing plants and flowers" },
    { word: "cactus", hint: "A desert plant with spines instead of leaves" },
    { word: "pyramid", hint: "A triangular structure from ancient Egypt" },
    { word: "glacier", hint: "A slow-moving mass of ice" },
    { word: "telescope", hint: "An instrument for viewing distant objects" },
    { word: "parrot", hint: "A colorful bird that can mimic sounds" },
    { word: "umbrella", hint: "A tool used to protect against rain" },
    { word: "lighthouse", hint: "A tower with a light to guide ships" },
    { word: "fireworks", hint: "Explosive devices that create colorful displays" },
    { word: "treasure", hint: "A collection of valuable items" },
    { word: "avalanche", hint: "A sudden flow of snow down a slope" },
    { word: "tornado", hint: "A violent rotating column of air" },
    { word: "horizon", hint: "The line where the sky meets the earth" },
    { word: "tsunami", hint: "A giant sea wave caused by an earthquake" },
    { word: "carnival", hint: "A festival with rides and entertainment" },
    { word: "rainbow", hint: "A multicolored arc in the sky" },
    { word: "butterfly", hint: "An insect with colorful wings" },
    { word: "submarine", hint: "A vessel that travels underwater" },
    { word: "circuit", hint: "A closed loop that allows electricity to flow" },
    { word: "lantern", hint: "A portable light source" },
    { word: "seashell", hint: "A hard protective outer layer of sea creatures" },
    { word: "sculpture", hint: "A three-dimensional artwork" },
    { word: "astronaut", hint: "A person trained for space travel" },
    { word: "sphinx", hint: "A mythical creature with a lion's body and a human head" },
    { word: "clocktower", hint: "A tall structure with a timepiece" },
    { word: "compass", hint: "A tool used for navigation" },
    { word: "fountain", hint: "A structure that jets water into the air" },
    { word: "zeppelin", hint: "A large airship" },
    { word: "vortex", hint: "A swirling mass of liquid or air" },
    { word: "quicksand", hint: "Loose sand that gives way under weight" },
    { word: "aurora", hint: "A natural light display in the sky" },
    { word: "geyser", hint: "A hot spring that erupts with steam and water" },
    { word: "cathedral", hint: "A large and important church" },
    { word: "monolith", hint: "A large single block of stone" },
    { word: "carousel", hint: "A rotating amusement ride with horses" },
    { word: "fjord", hint: "A deep sea inlet with steep cliffs" },
    { word: "gondola", hint: "A long narrow boat used in Venice" },
    { word: "mystic", hint: null },
    { word: "phantom", hint: "A ghost or spirit" },
    { word: "mirage", hint: "An optical illusion in the desert" },
    { word: "chandelier", hint: "An ornate hanging light fixture" },
    { word: "alchemy", hint: "An ancient practice of turning metals into gold" },
    { word: "crypt", hint: "An underground burial chamber" },
    { word: "serenade", hint: "A musical performance given to a loved one" },
    { word: "oracle", hint: "A person who gives prophetic messages" },
    { word: "quasar", hint: "A celestial object emitting immense energy" },
    { word: "labyrinth", hint: "A complex maze" },
    { word: "riddle", hint: "A puzzling question or statement" },
    { word: "gargoyle", hint: "A grotesque carved stone figure" },
    { word: "nebula", hint: "A cloud of gas and dust in space" },
    { word: "whirlpool", hint: "A rapidly rotating body of water" }
];
